from .winnougan_power_lora_loader import (
    NODE_CLASS_MAPPINGS as LORA_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_DISPLAY,
)
from .winnougan_resolution_picker import (
    NODE_CLASS_MAPPINGS as RES_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RES_DISPLAY,
)
from .Winnougan_LTX_Resolution_Picker import (
    NODE_CLASS_MAPPINGS as LTX_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTX_DISPLAY,
)

NODE_CLASS_MAPPINGS        = {**LORA_MAPPINGS, **RES_MAPPINGS, **LTX_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**LORA_DISPLAY,  **RES_DISPLAY,  **LTX_DISPLAY}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]